"""added unrecommend table

Revision ID: 646d90b8b542
Revises: cd1a2809996b
Create Date: 2020-12-16 16:31:02.635621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646d90b8b542'
down_revision = 'cd1a2809996b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unrecommend',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'content_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unrecommend')
    # ### end Alembic commands ###
