swagger: "2.0"
info:
  version: "1.0.0"
  title: "T3A3 - Netflix API"
tags:
- name: "users"
  description: "User related functions"
- name: "profile"
  description: "Profile functions"
- name: "groups"
  description: "Group functions"
- name: "content"
  description: "Content related functions"
- name: "admin"
  description: "Admin related functions"
paths:
  /users/register:
    post:
      tags:
      - "users"
      summary: "User registration"
      parameters:
        - in: "body"
          name: "body"
          description: "Creates new user in database"
          schema:
            type: "object"
            properties:
              email:
                type: "string"
              password:
                type: "string"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "email already exists"
  /users/login:
    post:
      tags: 
      - "users"
      summary: "Logs user into system"
      parameters:
      - name: "body"
        in: "body"
        description: "Logs in user"
        schema:
          type: "object"
          properties:
            email:
              type: "string"
            password:
              type: "string"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "incorrect login credentials"
  /users/:
    get:
      tags: 
      - "users"
      summary: "Get user by user id"
      description: "Gets user details of the logged in user"
      parameters:
      - name: "Bearer token"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Header required"
        "404":
          description: "User not found"
        "422":
          description: "Invalid token"
    patch:
      tags:
      - "users"
      summary: "Update user details"
      description: "Can only be done by the logged in user"
      parameters:
      - name: "Bearer token"
        in: "header"
        required: true
        type: "string"
      - name: "subscription"
        in: "body"
        description: "fields to be updated"
        schema:
          type: "object"
          properties:
            email:
              type: "string"
            subscription:
              type: "boolean"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "invalid user"
        "422":
          description: "Invalid token"
    delete:
      tags:
      - "users"
      summary: "Delete user"
      description: "Can only be done by a logged in user"
      parameters:
      - name: "Bearer token"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "invalid user"
        "404":
          description: "user not found"
  /profiles/:
    get:
      tags:
      - "profile"
      summary: "Get profiles"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid user"
        "422":
          description: "Invalid token"
  /profiles/{profile_id}:
    get:
      tags:
      - "profile"
      summary: "View profile by id"
      parameters:
      - name: "profile_id"
        in: "path"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid user"
        "404":
          description: "user not found"
    patch:
      tags:
      - "profile"
      summary: "Update profile details"
      parameters:
      - name: "profile_id"
        in: "path"
        required: true
        type: "integer"
      - name: "body"
        in: "body"
        description: "profile fields to be updated"
        schema:
          type: "object"
          properties:
            name:
              type: "string"
            restrictions:
              type: "string"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "invalid profile"
        "404":
          description: "profile not found"
    delete:
      tags:
      - "profile"
      summary: "Delete user"
      parameters:
      - name: "profile_id"
        in: "path"
        description: "profile_id of profile to be deleted"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "invalid user"
        "404":
          description: "profile not found"
  /profiles/create:
    post:
      tags:
      - "profile"
      summary: "Create new profile under user_id"
      parameters:
        - in: "body"
          name: "body"
          description: "Creates new profile under user_id"
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              restrictions:
                type: "string"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid user"
        "400":
          description: "Invalid fields entered"
  /profiles/{profile_id}/unrecommend:
    get:
      tags:
      - "profile"
      summary: "Display unrecommended content"
      parameters:
      - name: "profile_id"
        in: "path"
        description: "profile_id of profile to be deleted"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid user"
        "404":
          description: "not found"
    put:
      tags:
      - "profile"
      summary: "Add content to unrecommend list"
      parameters:
      - name: "profile_id"
        in: "path"
        description: "profile_id of profile to be deleted"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "adds content_id to list"
        schema:
          type: "object"
          properties:
            content_id:
              type: "integer"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid user"
        "404":
          description: "Profile/Content not found"
    delete:
      tags:
      - "profile"
      summary: "Remove content from unrecommend list"
      parameters:
      - name: "profile_id"
        in: "path"
        description: "profile_id of profile to be deleted"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "content_id to be removed"
        schema:
          type: "object"
          properties:
            content_id:
              type: "integer"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid user"
        "404":
          description: "Profile/Content not found"
  /groups/:
    post:
      tags:
      - "groups"
      summary: "Create new group"
      parameters:
      - name: "profile_id"
        in: "query"
        description: "Profile_id for profile search"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "Creates new group"
        schema:
          type: "object"
          properties:
            name:
              type: "string"
            description:
              type: "string"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid input"
        "404":
          description: "Profile not found"
    get:
      tags:
      - "groups"
      summary: "Display groups"
      parameters:
      - name: "profile_id"
        in: "query"
        description: "Profile_id for profile search"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "invalid user"
        "404":
          description: "Profile not found"
  /groups/{group_id}:
    get:
      tags:
      - "groups"
      summary: "Display group by id"
      parameters:
      - name: "group_id"
        in: "path"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "invalid user"
        "404":
          description: "not found"
    patch:
      tags:
      - "groups"
      summary: "Update group details"
      description: "Only can be done by group admin"
      parameters:
      - name: "profile_id"
        in: "query"
        description: "Profile_id for profile search"
        required: true
        type: "integer"
      - name: "group_id"
        in: "path"
        required: true
        type: "integer"
      - name: "body"
        in: "body"
        description: "fields to be updated"
        schema:
          type: "object"
          properties:
            name:
              type: "string"
            description:
              type: "string"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid field(s)"
        "401":
          description: "Invalid user/Unauthorised to update"
        "404":
          description: "Profile/Group not found"
    delete:
      tags:
      - "groups"
      summary: "Delete group"
      description: "Can only be performed by group admin"
      parameters:
      - name: "profile_id"
        in: "query"
        description: "Profile_id for profile search"
        required: true
        type: "integer"
      - name: "group_id"
        in: "path"
        description: "group_id of group to be deleted"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "invalid user/Unauthorised to delete"
        "404":
          description: "group not found"
  /groups/{group_id}/join:
    post:
      tags:
      - "groups"
      summary: "Adds user to group"
      parameters:
      - name: "group_id"
        in: "path"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "Adds new profile_id to group"
        schema:
          type: "object"
          properties:
            profile_id:
              type: "integer"
      responses:
        "200":
          description: "successful operation"
        "401": 
          description: "Already a member"
        "404":
          description: "User/Profile not found"
  /groups/{group_id}/unjoin:
    delete:
      tags:
      - "groups"
      summary: "Unjoin group"
      description: "Can be peformed by associated profile"
      parameters:
      - name: "group_id"
        in: "path"
        description: "group_id of group to unjoined"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "profile_id to be removed"
        schema:
          type: "object"
          properties:
            profile_id:
              type: "integer"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Not a member"
        "404":
          description: "Group/profile not found"
  /groups/{group_id}/remove_member:
    delete:
      tags:
      - "groups"
      summary: "Remove member"
      description: "Can only be peformed by group admin"
      parameters:
      - name: "group_id"
        in: "path"
        description: "group_id of member to be deleted"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "profile_id to be removed"
        schema:
          type: "object"
          properties:
            admin_id:
              type: "integer"
            profile_id:
              type: "integer"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "invalid user/not admin of this group"
        "404":
          description: "profile/member/group not found"
  /group/{group_id}/content:
    post:
      tags:
      - "groups"
      summary: "Adds content to group"
      parameters:
      - name: "group_id"
        in: "path"
        required: true
        type: "integer"
      - name: "profile_id"
        in: "query"
        description: "Profile_id for profile search"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "adds content_id to group"
        schema:
          type: "object"
          properties:
            content_id:
              type: "integer"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid member/content"
        "404":
          description: "Content not found"
    delete:
      tags:
      - "groups"
      summary: "Remove content"
      parameters:
      - name: "group_id"
        in: "path"
        description: "group_id of content to be deleted"
        required: true
        type: "integer"
      - name: "profile_id"
        in: "query"
        description: "Profile_id for profile search"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "content_id to be removed"
        schema:
          type: "object"
          properties:
            content_id:
              type: "integer"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid user/Invalid group"
        "404":
          description: "Group/Content not found"
  /content:
    get:
      tags:
        - "content"
      summary: "Display all content"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid user"
        "422":
          description: "Invalid token"
  /admin/login:
    post:
      tags:
      - "admin"
      summary: "Logs admin into admin interface"
      parameters:
      - name: "body"
        in: "body"
        description: "Admin log in"
        schema:
          type: "object"
          properties:
            username:
              type: "string"
            password:
              type: "string"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "incorrect login credentials"
  /admin/users:
    get:
      tags:
      - "admin"
      summary: "Display user data summary"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid user"
        "422":
          description: "Invalid token"
  /admin/groups:
    get:
      tags:
      - "admin"
      summary: "Display group data summary"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid user"
        "422":
          description: "Invalid token"
  /admin/groupcontent:
    get:
      tags:
      - "admin"
      summary: "Display group content data summary"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid user"
        "422":
          description: "Invalid token"
  /admin/content:
    get:
      tags:
      - "admin"
      summary: "Display content data summary"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid user"
        "422":
          description: "Invalid token"
    post:
      tags:
        - "admin"
      summary: "Create content"
      parameters:
      - in: "body"
        name: "body"
        description: "Create new content"
        schema:
          type: "object"
          properties:
            title:
              type: "string"
            genre:
              type: "string"
            year:
              type: "integer"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid input"
        "401":
          description: "Invalid admin"
  /admin/content/{content_id}:
    delete:
      tags:
      - "admin"
      summary: "remove content"
      parameters:
      - name: "content_id"
        in: "path"
        description: "id of content to be removed"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid admin"
        "404":
          description: "content not found"
  /admin/backupdb:
    get:
      tags:
      - "admin"
      summary: "Downloads all data from database table into local backup directory"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid admin"
  /admin/backups:
    get:
      tags:
      - "admin"
      summary: "Show all backup folders"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid admin"
  /admin/{name}:
    post:
      tags:
      - "admin"
      summary: "Restore data from selected backup file"
      parameters:
      - name: "name"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Invalid admin"