name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - name: Set Up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Tests
      env:
        FLASK_ENV: testing
      run: |
        cd src
        python -m unittest discover -s tests/ -v
    - name: Style Check
      run: |
        cd src
        flake8 .
  deployment:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with:
          host: 54.210.89.167
          username: github-actions
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            rm -rf T3A3
            git clone https://github.com/ashley190/T3A3.git
            cp .env /home/github-actions/T3A3/src
            python3.8 -m venv /home/github-actions/T3A3/venv
            /home/github-actions/T3A3/venv/bin/pip3.8 install -r /home/github-actions/T3A3/requirements.txt
